const mongoose=require('mongoose')
const validator=require('validator')
const prodSchema=new mongoose.Schema({
    prodName:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    brand:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    category:{
        type:String,
        required:true
    },
    images:[
        {
            public_id:{
                type:String,
                required:true
            },
            url:{
                type:String,
                required:true
            }
        }
    ],
    seller:{
        type:String,
        required:true
    },
    sellerEmail:{
        type:String,
        required:true,
        lowercase:true,
    },
    stock:{
        type:Number
    },
    rating:{
        type:Number,
        default:0
    },
    numOfRev:{
        type:Number,
        default:0
    },
    reviews:[
        {
            name:{
                type:String,
                required:true
            },
            rating:{
                type:Number,
                required:true
            },
            comment:{
                type:String,
                required:true
            }
        }
    ]
},{timestamps:true})
const Product=mongoose.model('Product',prodSchema)
module.exports=Product